# Weather Data EDA

## 1. Load Raw Data

In [38]:
#Create a project root for accessing other files
import sys
from pathlib import Path

Project_root = Path.cwd().parent
sys.path.append(str(Project_root))

#Importing the existing code
from src.config import Config

#Find raw JSON
import json

json_files = list(Config.raw_data_path.glob("*.json"))

latest_file = max(json_files, key=lambda file: file.stat().st_mtime)

with open(latest_file, "r", encoding="utf-8")as file:
    raw_data = json.load(file)

## 2. Normalize Raw JSON

In [39]:

from src.transformation import normalize_json

#Use the normalize function
df = normalize_json(raw_data)

import pandas as pd

## 3. Pre-Transformation Data Quality Assessment

### 3.1 Dataset Structure

In [40]:
df.shape

(98, 22)

In [41]:
df.head()

,location.province,location.areatype,location.name,location.tambon,location.region,location.geocode,location.amphoe,location.lat,location.lon,time,...,data.cloudmed,data.cond,data.rain,data.rh,data.slp,data.tc,data.tc_max,data.tc_min,data.wd10m,data.ws10m
0,กระบี่,province,กระบี่,None,S,81,None,8.062061,98.918394,2026-08-18T00:00:00+07:00,...,36.25,3,0.1,82.01,1011.71,27.84,31.03,24.25,263.09,7.36
1,กระบี่,province,กระบี่,None,S,81,None,8.062061,98.918394,2026-08-19T00:00:00+07:00,...,2.67,3,0.6,79.34,1011.25,27.59,30.91,24.60,267.67,8.83
2,กระบี่,province,กระบี่,None,S,81,None,8.062061,98.918394,2026-08-20T00:00:00+07:00,...,20.50,4,3.4,75.11,1011.16,28.58,32.00,25.56,260.73,9.08
3,กระบี่,province,กระบี่,None,S,81,None,8.062061,98.918394,2026-08-21T00:00:00+07:00,...,7.13,4,2.9,82.68,1011.33,27.83,31.35,23.04,234.95,7.51
4,กระบี่,province,กระบี่,None,S,81,None,8.062061,98.918394,2026-08-22T00:00:00+07:00,...,5.00,3,1.2,85.99,1011.86,27.49,30.06,25.56,210.24,7.12

In [42]:
df.columns.tolist()
#list all columns

['location.province',
 'location.areatype',
 'location.name',
 'location.tambon',
 'location.region',
 'location.geocode',
 'location.amphoe',
 'location.lat',
 'location.lon',
 'time',
 'data.cloudhigh',
 'data.cloudlow',
 'data.cloudmed',
 'data.cond',
 'data.rain',
 'data.rh',
 'data.slp',
 'data.tc',
 'data.tc_max',
 'data.tc_min',
 'data.wd10m',
 'data.ws10m']

### 3.2 Data Types

In [43]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 98 entries, 0 to 97
Data columns (total 22 columns):
 #   Column             Non-Null Count  Dtype
---  ------             --------------  -----
 0   location.province  98 non-null     str
 1   location.areatype  98 non-null     str
 2   location.name      98 non-null     str
 3   location.tambon    0 non-null      object
 4   location.region    98 non-null     str
 5   location.geocode   98 non-null     str
 6   location.amphoe    0 non-null      object
 7   location.lat       98 non-null     float64
 8   location.lon       98 non-null     float64
 9   time               98 non-null     str
 10  data.cloudhigh     98 non-null     float64
 11  data.cloudlow      98 non-null     float64
 12  data.cloudmed      98 non-null     float64
 13  data.cond          98 non-null     int64
 14  data.rain          98 non-null     float64
 15  data.rh            98 non-null     float64
 16  data.slp           98 non-null     float64
 17  data.tc            98 non-null     float64
 18  data.tc_max        98 non-null     float64
 19  data.tc_min        98 non-null     float64
 20  data.wd10m         98 non-null     float64
 21  data.ws10m         98 non-null     float64
dtypes: float64(13), int64(1), object(2), str(6)
memory usage: 17.0+ KB

In [44]:
df.dtypes
#We found here that the "time" is still a string

location.province        str
location.areatype        str
location.name            str
location.tambon       object
location.region          str
location.geocode         str
location.amphoe       object
location.lat         float64
location.lon         float64
time                     str
data.cloudhigh       float64
data.cloudlow        float64
data.cloudmed        float64
data.cond              int64
data.rain            float64
data.rh              float64
data.slp             float64
data.tc              float64
data.tc_max          float64
data.tc_min          float64
data.wd10m           float64
data.ws10m           float64
dtype: object

### 3.3 Missing Values

In [45]:
df.isna().sum()
#The data doesn't contain specific tambon and amphoe.

location.province     0
location.areatype     0
location.name         0
location.tambon      98
location.region       0
location.geocode      0
location.amphoe      98
location.lat          0
location.lon          0
time                  0
data.cloudhigh        0
data.cloudlow         0
data.cloudmed         0
data.cond             0
data.rain             0
data.rh               0
data.slp              0
data.tc               0
data.tc_max           0
data.tc_min           0
data.wd10m            0
data.ws10m            0
dtype: int64

### 3.4 Duplicate Records

In [46]:
df.duplicated().sum()

np.int64(0)

### 3.5 Numerical Value Ranges

In [48]:
numeric_col = df.select_dtypes(include=["float64"])

In [49]:
numeric_col.describe()

,location.lat,location.lon,data.cloudhigh,data.cloudlow,data.cloudmed,data.rain,data.rh,data.slp,data.tc,data.tc_max,data.tc_min,data.wd10m,data.ws10m
count,98.000000,98.000000,98.000000,98.000000,98.000000,98.000000,98.000000,98.000000,98.000000,98.000000,98.000000,98.000000,98.000000
mean,7.946897,99.829879,38.010408,63.213367,19.632449,4.686735,80.417653,1011.099694,27.715714,31.462653,24.828061,240.606020,8.300408
std,1.215173,1.061427,16.720408,21.586498,16.363326,9.611319,6.292809,0.480816,0.735652,1.708760,1.258987,63.699451,2.335849
min,6.428561,98.385376,4.380000,0.000000,0.000000,0.000000,50.560000,1009.340000,26.460000,28.130000,22.200000,39.920000,3.870000
25%,6.868660,98.918394,24.232500,48.630000,6.942500,0.000000,76.925000,1010.827500,27.172500,30.245000,23.857500,234.057500,6.662500
50%,7.754199,99.786312,39.690000,66.420000,16.875000,1.000000,81.180000,1011.155000,27.580000,31.050000,24.730000,251.875000,8.110000
75%,8.442509,100.596251,50.947500,80.927500,28.130000,5.725000,85.482500,1011.352500,28.260000,33.007500,25.682500,268.582500,9.765000
max,10.492748,101.822871,78.380000,95.670000,70.250000,76.500000,90.040000,1011.980000,30.390000,34.950000,27.650000,358.760000,16.790000

### 3.6 Categorical Values

In [53]:
df["data.cond"].value_counts()

data.cond
3    34
4    32
1    18
5     7
2     7
Name: count, dtype: int64

In [55]:
df["location.province"].value_counts()

location.province
กระบี่           7
ชุมพร            7
ตรัง             7
นครศรีธรรมราช    7
นราธิวาส         7
ปัตตานี          7
พังงา            7
พัทลุง           7
ภูเก็ต           7
ยะลา             7
ระนอง            7
สงขลา            7
สตูล             7
สุราษฎร์ธานี     7
Name: count, dtype: int64

In [56]:
df["data.cond"].nunique()

5

In [57]:
df["data.cond"].unique()

array([3, 4, 5, 2, 1])

### 3.7 Temporal Data

In [47]:
df["time"] = pd.to_datetime(df["time"])

In [50]:
df["time"].head()

0   2026-08-18 00:00:00+07:00
1   2026-08-19 00:00:00+07:00
2   2026-08-20 00:00:00+07:00
3   2026-08-21 00:00:00+07:00
4   2026-08-22 00:00:00+07:00
Name: time, dtype: datetime64[us, UTC+07:00]

In [51]:
df["time"].min()

Timestamp('2026-08-18 00:00:00+0700', tz='UTC+07:00')

In [52]:
df["time"].max()

Timestamp('2026-08-24 00:00:00+0700', tz='UTC+07:00')

In [58]:
df["time"].isnull().sum()

np.int64(0)

In [ ]:
df["time"].diff().value_counts()
#It counts how many times each difference happened. Example: There were 84 instances where the next row was exactly 1 day after the previous row and there are 13 instances where the next row was 6 days earlier than the previous row.

time
1 days     84
-6 days    13
Name: count, dtype: int64

## EDA Summary

- The dataset contains 98 rows and 22 columns after JSON normalization.
- No unexpected missing values were identified. NULL values in `amphoe` and `tambon` are expected because the dataset is retrieved at the province/region level. These fields are intentionally left NULL.
- No duplicate records were identified.
- Numerical variables have reasonable ranges based on their weather-related meaning.
- Categorical weather conditions contain expected values.
- The `time` column is currently stored as a string and should be converted to datetime during transformation.
- Weather measurement columns are already represented using approproate numeric data types.